/*
 * Error Include File    Created on ...
 *
 * This file has been generated by errXmlToH utility
 * 
 * !!!!!!!!!!!  DO NOT MANUALLY EDIT THIS FILE  !!!!!!!!!!!
 */

#define vobsERR_CDATA_NOT_FOUND 7   /**<  CDATA section not found */
#define vobsERR_GDOME_CALL 6   /**<  Call to %s function failed with the exception  "%d */
#define vobsERR_INVALID_CDATA_FORMAT 8   /**<  Invalid format of the CDATA line '%.100s' */
#define vobsERR_INVALID_UCD_NAME 9   /**<  Invalid UCD name '%s' */
#define vobsERR_INVALID_UCD_ID 10   /**<  Invalid UCD id '%d' */
#define vobsERR_INVALID_UCD_FORMAT 11   /**<  Invalid UCD format '%.80s'; should be %.20s */
#define vobsERR_INVALID_RA_FORMAT 12   /**<  Invalid RA format '%.80s'; should be 'HH MM SS.TTT' */
#define vobsERR_RA_NOT_SET 13   /**<  RA property not set */
#define vobsERR_INVALID_DEC_FORMAT 14   /**<  Invalid DEC format '%.80s'; should be 'DD MM SS.TTT' */
#define vobsERR_DEC_NOT_SET 15   /**<  DEC property not set */
#define vobsERR_INVALID_CONSTRAINT 16   /**<  Invalid CONSTRAINT id '%d' */
#define vobsERR_INVALID_CONSTRAINT_FORMAT 17   /**<  Invalid CONSTRAINT format '%.80s'; should be %.20s */
#define vobsERR_INVALID_KIND_OF_REQUEST 18   /**<  Invalid Kind of request '%d'; should be 0 or 1 */
#define vobsERR_KIND_OF_REQUEST_NOT_SET 19   /**<  Kind of request not set */
#define vobsERR_CHECK_OF_KIND_OF_REQUEST_FAILED 20   /**<  Kind of request not set */
#define vobsERR_CHECK_FOR_SIMPLE_STAR_FAILED 21   /**<  constraint for simple star search not ok */
#define vobsERR_CHECK_FOR_STAR_LIST_FAILED 22   /**<  constraints for star list search not ok */
#define vobsERR_BAD_CATALOG_NAME 23   /**<  bad catalog name */
#define vobsERR_ASKING_WRITE_FAILED 24   /**<  The asking is not writing correctly : %s */
#define vobsERR_URI_WRITE_FAILED 25   /**<  The URI is not writing correctly */
#define vobsERR_CONSTANT_WRITE_FAILED 26   /**<  The Constants are not writing correctly */
#define vobsERR_POSITION_WRITE_FAILED 27   /**<  The position are not writing correctly */
#define vobsERR_END_WRITE_FAILED 28   /**<  The end is not writing correctly */
