/*
 * Error Include File    Created on ...
 *
 * This file has been generated by errXmlToH utility
 * 
 * !!!!!!!!!!!  DO NOT MANUALLY EDIT THIS FILE  !!!!!!!!!!!
 */

 /**
 * \file 
 * Generated file for the define list of errors.
 */
#define vobsERR_CDATA_NOT_FOUND 7   /**<  CDATA section not found */
#define vobsERR_GDOME_CALL 6   /**<  Call to %80s function failed with the exception '%d' */
#define vobsERR_INVALID_CDATA_FORMAT 8   /**<  Invalid format of the CDATA line '%.100s' */
#define vobsERR_INVALID_UCD_NAME 9   /**<  Invalid UCD name '%80s' */
#define vobsERR_INVALID_UCD_ID 10   /**<  Invalid UCD id '%80s' */
#define vobsERR_INVALID_UCD_FORMAT 11   /**<  Invalid UCD format '%.80s'; should be %.20s */
#define vobsERR_INVALID_RA_FORMAT 12   /**<  Invalid RA format '%.80s'; should be 'HH MM SS.TTT' */
#define vobsERR_RA_NOT_SET 13   /**<  RA property not set */
#define vobsERR_INVALID_DEC_FORMAT 14   /**<  Invalid DEC format '%.80s'; should be 'DD MM SS.TTT' */
#define vobsERR_DEC_NOT_SET 15   /**<  DEC property not set */
#define vobsERR_INVALID_CONSTRAINT 16   /**<  Invalid CONSTRAINT id '%80s' */
#define vobsERR_INVALID_CONSTRAINT_FORMAT 17   /**<  Invalid CONSTRAINT format '%.80s'; should be %.20s */
#define vobsERR_UNKNOWN_CATALOG_NAME 23   /**<  Unknown catalog name '%.80s' */
#define vobsERR_PROPERTY_NOT_SET 30   /**<  Could not read value of '%.80s' property, it has not been set. */
#define vobsERR_PROPERTY_TYPE 31   /**<  Could not set or get property "%.40s". Could not convert value '%.40s' using format '%.40s' */
#define vobsERR_INVALID_PROP_FORMAT 32   /**<  Invalid property '%.80s' value '%.80s'; should be %.20s */
#define vobsERR_DUPLICATED_PROPERTY 33   /**<  Duplicated property name '%80s' */
#define vobsERR_INVALID_PROPERTY_ID 34   /**<  Invalid property id '%80s' */
#define vobsERR_NO_MORE_CRITERIA 35   /**<  No more criteria in the list */
#define vobsERR_CATALOG_LOAD 38   /**<  Could not load '%80s' catalog  */
#define vobsERR_INVALID_PARSING_UCD_FORMAT 40   /**<  Invalid format for UCD parsing */
#define vobsERR_PARSE_CDATA 42   /**<  Could not parse CDATA */
#define vobsERR_INVALID_BAND 43   /**<  Incorrect band. It should be '%.80s' band */
#define vobsERR_INCONSISTENT_PARAMS_DESC 44   /**<  Inconsistent parameters description; number of pararameter name (%d) differs from number of UCDs (%d). */
#define vobsERR_MISSING_UCDS 45   /**<  Line containing the list of UCDs is missing. */
#define vobsERR_MISSING_PARAM_NAMES 46   /**<  Line containing the list of parameter names is missing. */
#define vobsERR_NO_CDS_RETURN 47   /**<  Connexion to CDS failed */
#define vobsERR_CATALOG_LIST_EMPTY 48   /**<  The list of catalog is empty, it is impossible to retreive catalog */
#define vobsERR_EMPTY_STAR_LIST 55   /**<  The given star list is empty */
#define vobsERR_UNKNOWN_CATALOG 50   /**<  Catalog '%.80s' is unknown */
#define vobsERR_CONDITION_TYPE 51   /**<  New condition type (%80s) differs from the other ones (%80s) */
#define vobsERR_INCOMPATIBLE_TYPES 53   /**<  Condition type (%80s) and property type (%80s) are not compatible */
#define vobsERR_QUERY_OPTION_NOT_SUPPORTED 57   /**<  Option %80s is not supported for local catalog */
