/*
 * Error Include File    Created on ...
 *
 * This file has been generated by errXmlToH utility
 * 
 * !!!!!!!!!!!  DO NOT MANUALLY EDIT THIS FILE  !!!!!!!!!!!
 */

#define vobsERR_BAD_PARAMETERS 1
#define vobsERR_ACTION 2
#define vobsERR_MEMORY 3
#define vobsERR_ACTION_GDOME 4
