/*
 * Error Include File    Created on ...
 *
 * This file has been generated by errXmlToH utility
 * 
 * !!!!!!!!!!!  DO NOT MANUALLY EDIT THIS FILE  !!!!!!!!!!!
 */

 /**
 * \file 
 * Generated file for the define list of errors.
 */
#define alxERR_WRONG_FILE_FORMAT 5   /**<  Wrong format of the line '%.120s' in file '%.120s' */
#define alxERR_TOO_MANY_LINES 6   /**<  Too many line in file '%.120s' */
#define alxERR_WRONG_SPECTRAL_TYPE_FORMAT 7   /**<  Wrong format of the spectral type '%.20s'; must be <code&gt;<quantity&gt;<light-class&gt; */
#define alxERR_SPECTRAL_TYPE_NOT_FOUND 9   /**<  Spectral type '%.20s' (code=%c, quantity=%.2lf) not found in color table '%80s'. */
#define alxERR_INVALID_BAND 10   /**<  Invalid band '%c' found in file '%.120s'. */
#define alxERR_MISSING_LINE 11   /**<  There is missing line (%d instead of %d) line in file '%.120s' */
#define alxERR_DUPLICATED_LINE 12   /**<  Line '%.80s' is duplicated in file '%.120s' */
#define alxERR_INVALID_PARALAX_VALUE 13   /**<  Invalid value '%.3f' for paralax; should be a non-zero value. */
#define alxERR_LONGITUDE_NOT_FOUND 14   /**<  Spectral type '%.20s' not found in interstellar extinction table. */
#define alxERR_TOO_MANY_COLUMS 15   /**<  Too many columns in file '%.120s' at line %d */
#define alxERR_MISSING_COLUMS 16   /**<  Missing columns in file '%.120s' at line %d; %d foundsinstead of %d expected */
#define alxERR_NULL_PARAMETER 17   /**<  The given '%80s' parameter is NULL. */
#define alxERR_DIFFJK_NOT_IN_TABLE 18   /**<  J-K differential magnitude (%.3lf) not found in color table '%80s' */
#define alxERR_NO_LINE_FOUND 20   /**<  no line found, can't interpolate */
