/*
 * Error Include File    Created on ...
 *
 * This file has been generated by errXmlToH utility
 * 
 * !!!!!!!!!!!  DO NOT MANUALLY EDIT THIS FILE  !!!!!!!!!!!
 */

#define sclsvrERR_INVALID_PROPERTY_ID 1   /**<  Invalid property id '%d' */
#define sclsvrERR_INVALID_PROPERTY_NAME 2   /**<  Invalid property name '%s' */
#define sclsvrERR_INVALID_PROPERTY_FORMAT 3   /**<  Invalid property format '%.80s'; should be %.20s */
