/*
 * Error Include File    Created on ...
 *
 * This file has been generated by errXmlToH utility
 * 
 * !!!!!!!!!!!  DO NOT MANUALLY EDIT THIS FILE  !!!!!!!!!!!
 */

 /**
 * \file 
 * Generated file for the define list of errors.
 */
#define sclsvrERR_PROPERTY_NOT_SET 4   /**<  Property value not set : "%80s" */
#define sclsvrERR_STAR_NOT_FOUND 5   /**<  Star named '%.80s' has not been found in %80s */
#define sclsvrERR_WRONG_BUFFER_FORMAT 6   /**<  Invalid format of buffer '%.80s' */
#define sclsvrERR_MISSING_PROPERTY 7   /**<  Property '%.20s' is missing; could not compute '%.80s' */
#define sclsvrERR_NO_REQUEST_LINE 8   /**<  Invalid file format '%.80s'; it should contain the user request in the first line. */
#define sclsvrERR_REQUEST_LINE_FORMAT 9   /**<  Invalid file format '%.40s'; the first line '%.80s' does not correspond to the user request. */
#define sclsvrERR_INVALID_SEARCH_AREA 10   /**<  A %80s query need a %80s search area */
#define sclsvrERR_NO_CDS_RETURN 12   /**<  Connection to CDS failed or a CDS error occured */
#define sclsvrERR_UNKNOWN_FAINT_BAND 13   /**<  Invalid band '%80s' for the FAINT scenario: should be I, J, H or K */
#define sclsvrERR_UNKNOWN_BRIGHT_BAND 14   /**<  Invalid band '%80s' for the BRIGHT scenario: should be V, I, J, H, K or N */
#define sclsvrERR_UNSUPPORTED_OUTPUT_FORMAT 15   /**<  Unsupported output format '%.1lf' ('%.1lf' expected); please download the latest SearchCal GUI at http://www.jmmc.fr/searchcal */
#define sclsvrERR_CATALOG_LOAD_JSDC 16   /**<  Could not load JSDC catalog from '%80s' */
