#*******************************************************************************
# JMMC project
#
# "@(#) $Id: Makefile,v 1.5 2005-10-26 11:30:41 lafrasse Exp $"
#
# Makefile of the alx module 
#
# History
# -------
# $Log: not supported by cvs2svn $
# Revision 1.4  2005/02/15 14:47:55  gzins
# Removed unused target
#
# Revision 1.3  2005/02/12 15:11:51  gzins
# Added rules for alxGetResearchAreaSize function
#
# Revision 1.2  2005/01/21 08:10:30  gluck
# - Updated
# - Insert automatic rcs log in header file
#
#
# scetre    20-Sep-2004  Created
#
#*******************************************************************************
# REMARKS
#    Makefile based on the VLT/ALMA Makefile
#
#-------------------------------------------------------------------------------

#
# user definable C-compilation flags
#USER_CFLAGS =

#
# user definable javac compilation flags
#USER_JFLAGS = 

#
# additional include and library search paths
#USER_INC = 
#USER_LIB = 

#
# MODULE CODE DESCRIPTION:
# ------------------------
# As a general rule:  public file are "cleaned" and "installed"  
#                     local (_L) are not "installed".

#
# C programs (public and local)
# -----------------------------
EXECUTABLES     =
EXECUTABLES_L   = 

#
# <brief description of xxxxx program>
xxxxx_OBJECTS   =
xxxxx_LDFLAGS   =
xxxxx_LIBS      =

#
# special compilation flags for single c sources
#yyyyy_CFLAGS   =

#
# Includes (.h) files (public only)
# ---------------------------------
INCLUDES        = alx.h
				  
#
# Libraries (public and local)
# ----------------------------
LIBRARIES       = alx 
LIBRARIES_L     =

#
# <brief description of lllll library>
alx_OBJECTS   = alxAngularDiameter          \
				alxGalacticCoordinates      \
				alxMagnitude                \
				alxRealMagnitude            \
				alxVisibility               \
				alxResearchArea             \
				alxDistance

#
# Scripts (public and local)
# --------------------------
SCRIPTS         =
SCRIPTS_L       =

#
# TCL scripts (public and local)
# ------------------------------
TCL_SCRIPTS     =
TCL_SCRIPTS_L   =

#
# <brief description of tttttt tcl-script>
tttttt_OBJECTS  =
tttttt_TCLSH    = 
tttttt_LIBS     = 

#
# TCL libraries (public and local)
# --------------------------------
TCL_LIBRARIES   =
TCL_LIBRARIES_L =

#
# <brief description of tttlll library>
tttlll_OBJECTS  = 

#
# Python scripts (public and local)
# ---------------------------------
PY_SCRIPTS     =
PY_SCRIPTS_L   =

#
# Jarfiles and their directories
# ---------------------------------
JARFILES        =

#
# <brief description of jjjfff jar files>
jjjfff_DIRS     =
jjjfff_EXTRAS   = 

# Java programs
# ---------------------------------
JAVA_EXECUTABLES=

#
# <brief description of jjjjjj java program>
jjjjjj_CLASS    =

#
# man pages to be done
# --------------------
MANSECTIONS =
MAN1 =
MAN3 =
MAN5 =
MAN7 =
MAN8 =

#
# other files to be installed
#----------------------------
INSTALL_FILES = ../config/alxAbsIntPolynomial.cfg					\
				../config/alxAngDiamPolynomialForBrightStar.cfg		\
				../config/alxColorTableForBrightDwarfStar.cfg		\
				../config/alxColorTableForBrightGiantStar.cfg		\
				../config/alxColorTableForBrightSuperGiantStar.cfg	\
				../config/alxExtinctionRatioTable.cfg	\
				../config/alxStarPopulationInKBand.cfg

#
# list of all possible C-sources (used to create automatic dependencies)
# ----------------------------------------------------------------------
CSOURCENAMES = \
	$(foreach exe, $(EXECUTABLES) $(EXECUTABLES_L), $($(exe)_OBJECTS)) \
	$(foreach lib, $(LIBRARIES) $(LIBRARIES_L), $($(lib)_OBJECTS))

#
#>>>>> END OF standard rules

#
# INCLUDE STANDARDS
# -----------------
MAKEDIR = $(MCSROOT)/include
include $(MAKEDIR)/mkfMakefile

#
# TARGETS
# -------
all:	do_all
	@echo " . . . 'all' done" 

clean : clean_all 
	@echo " . . . clean done"

man   : do_man 
	@echo " . . . man page(s) done"

install : install_all
	@echo " . . . installation done"

#___oOo___
