  COMMON PHOTOMETRY, CF,CI,CJ,IBAND,JBAND,USEDBANDS,EMAG_MIN,NCOLORS,PARAMS,E_PARAMS
  COMMON GENERALPARAMS, LUM_CLASSES,MODE,DEG,NSIG,SEED,STAT,SNR
  COMMON POLYNOMS, PAR, EPAR, MCOV_POL, CHI2_POL, SPECTRAL_DSB,E_SPECTRAL_DSB, NSPECTRALTYPES
  COMMON DATABASE, DATA_B,NSTAR_B,DIAM_I,EDIAM_I,MAG_B,EMAG_B,DIAM_B,EDIAM_B,LUMCLASS_B,DLUMCLASS_B,$
     SPTYPE_B,DSPTYPE_B,ORIG_SPTYPE,DMEAN_B,EDMEAN_B,RES_B,CHI2_MD,GOOD_B,GOOD_FIX
  COMMON CATALOG, DATA_C,NSTAR_C,MAG_C,EMAG_C,DIAM_C,EDIAM_C,LUMCLASS_C,DLUMCLASS_C,SPTYPE_C,DSPTYPE_C,DMEAN_C,EDMEAN_C,RES_C,CHI2_DS,GOOD_C
  COMMON OPTIONS, DOWAIT, DOPRINT, UNITLOG

