/*
 * Error Include File    Created on ...
 *
 * This file has been generated by errXmlToH utility
 * 
 * !!!!!!!!!!!  DO NOT MANUALLY EDIT THIS FILE  !!!!!!!!!!!
 */

 /**
 * \file 
 * Generated file for the define list of errors.
 */
#define sclwsERR_BIND 1   /**<  Could not bind on port '%d'. */
#define sclwsERR_THREAD_CREATION 2   /**<  Could not create a thread. */
#define sclwsERR_NULL_PTR 3   /**<  The pointer '%80s' is NULL. */
#define sclwsERR_GETCAL 4   /**<  Query failed. */
#define sclwsERR_CATALOG_NAME 5   /**<  Catalog name retrieving failed. */
#define sclwsERR_ALLOC_MEM 6   /**<  Could not allocate not %d bytes */
#define sclwsERR_SERVER_INSTANCIATION 7   /**<  Could not instantiate server */
#define sclwsERR_WRONG_SERVER_ID 8   /**<  Invalid '%80s' server id */
#define sclwsERR_STL_MUTEX 9   /**<  Could not use mutex that prevents concurrent access to STL shared objects */
#define sclwsERR_UUID_MUTEX 10   /**<  Could not use mutex that prevents concurrent access to UUID generate function */
#define sclwsERR_GETCAL_WORKING 11   /**<  GetCal Query already in progress */
