/* soapH.h
   Generated by gSOAP 2.7.11 from ../include/sclwsWS.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_bool
#define SOAP_TYPE_bool (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_bool(struct soap*, bool *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_bool(struct soap*, const bool *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_bool(struct soap*, const char*, int, const bool *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_bool2s(struct soap*, bool);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_get_bool(struct soap*, bool *, const char*, const char*);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_in_bool(struct soap*, const char*, bool *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2bool(struct soap*, const char*, bool *);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Fault * SOAP_FMAC6 soap_new_SOAP_ENV__Fault(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Reason * SOAP_FMAC6 soap_new_SOAP_ENV__Reason(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Detail * SOAP_FMAC6 soap_new_SOAP_ENV__Detail(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Code * SOAP_FMAC6 soap_new_SOAP_ENV__Code(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Header * SOAP_FMAC6 soap_new_SOAP_ENV__Header(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE_ns__GetServerStatus
#define SOAP_TYPE_ns__GetServerStatus (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__GetServerStatus(struct soap*, struct ns__GetServerStatus *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__GetServerStatus(struct soap*, const struct ns__GetServerStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__GetServerStatus(struct soap*, const struct ns__GetServerStatus *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__GetServerStatus(struct soap*, const char*, int, const struct ns__GetServerStatus *, const char*);
SOAP_FMAC3 struct ns__GetServerStatus * SOAP_FMAC4 soap_get_ns__GetServerStatus(struct soap*, struct ns__GetServerStatus *, const char*, const char*);
SOAP_FMAC3 struct ns__GetServerStatus * SOAP_FMAC4 soap_in_ns__GetServerStatus(struct soap*, const char*, struct ns__GetServerStatus *, const char*);
SOAP_FMAC5 struct ns__GetServerStatus * SOAP_FMAC6 soap_new_ns__GetServerStatus(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__GetServerStatus(struct soap*, struct ns__GetServerStatus*);
SOAP_FMAC3 struct ns__GetServerStatus * SOAP_FMAC4 soap_instantiate_ns__GetServerStatus(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__GetServerStatus(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__GetServerStatusResponse
#define SOAP_TYPE_ns__GetServerStatusResponse (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__GetServerStatusResponse(struct soap*, struct ns__GetServerStatusResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__GetServerStatusResponse(struct soap*, const struct ns__GetServerStatusResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__GetServerStatusResponse(struct soap*, const struct ns__GetServerStatusResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__GetServerStatusResponse(struct soap*, const char*, int, const struct ns__GetServerStatusResponse *, const char*);
SOAP_FMAC3 struct ns__GetServerStatusResponse * SOAP_FMAC4 soap_get_ns__GetServerStatusResponse(struct soap*, struct ns__GetServerStatusResponse *, const char*, const char*);
SOAP_FMAC3 struct ns__GetServerStatusResponse * SOAP_FMAC4 soap_in_ns__GetServerStatusResponse(struct soap*, const char*, struct ns__GetServerStatusResponse *, const char*);
SOAP_FMAC5 struct ns__GetServerStatusResponse * SOAP_FMAC6 soap_new_ns__GetServerStatusResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__GetServerStatusResponse(struct soap*, struct ns__GetServerStatusResponse*);
SOAP_FMAC3 struct ns__GetServerStatusResponse * SOAP_FMAC4 soap_instantiate_ns__GetServerStatusResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__GetServerStatusResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__GetStar
#define SOAP_TYPE_ns__GetStar (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__GetStar(struct soap*, struct ns__GetStar *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__GetStar(struct soap*, const struct ns__GetStar *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__GetStar(struct soap*, const struct ns__GetStar *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__GetStar(struct soap*, const char*, int, const struct ns__GetStar *, const char*);
SOAP_FMAC3 struct ns__GetStar * SOAP_FMAC4 soap_get_ns__GetStar(struct soap*, struct ns__GetStar *, const char*, const char*);
SOAP_FMAC3 struct ns__GetStar * SOAP_FMAC4 soap_in_ns__GetStar(struct soap*, const char*, struct ns__GetStar *, const char*);
SOAP_FMAC5 struct ns__GetStar * SOAP_FMAC6 soap_new_ns__GetStar(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__GetStar(struct soap*, struct ns__GetStar*);
SOAP_FMAC3 struct ns__GetStar * SOAP_FMAC4 soap_instantiate_ns__GetStar(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__GetStar(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__GetStarResponse
#define SOAP_TYPE_ns__GetStarResponse (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__GetStarResponse(struct soap*, struct ns__GetStarResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__GetStarResponse(struct soap*, const struct ns__GetStarResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__GetStarResponse(struct soap*, const struct ns__GetStarResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__GetStarResponse(struct soap*, const char*, int, const struct ns__GetStarResponse *, const char*);
SOAP_FMAC3 struct ns__GetStarResponse * SOAP_FMAC4 soap_get_ns__GetStarResponse(struct soap*, struct ns__GetStarResponse *, const char*, const char*);
SOAP_FMAC3 struct ns__GetStarResponse * SOAP_FMAC4 soap_in_ns__GetStarResponse(struct soap*, const char*, struct ns__GetStarResponse *, const char*);
SOAP_FMAC5 struct ns__GetStarResponse * SOAP_FMAC6 soap_new_ns__GetStarResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__GetStarResponse(struct soap*, struct ns__GetStarResponse*);
SOAP_FMAC3 struct ns__GetStarResponse * SOAP_FMAC4 soap_instantiate_ns__GetStarResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__GetStarResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__GetCalCancelSession
#define SOAP_TYPE_ns__GetCalCancelSession (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__GetCalCancelSession(struct soap*, struct ns__GetCalCancelSession *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__GetCalCancelSession(struct soap*, const struct ns__GetCalCancelSession *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__GetCalCancelSession(struct soap*, const struct ns__GetCalCancelSession *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__GetCalCancelSession(struct soap*, const char*, int, const struct ns__GetCalCancelSession *, const char*);
SOAP_FMAC3 struct ns__GetCalCancelSession * SOAP_FMAC4 soap_get_ns__GetCalCancelSession(struct soap*, struct ns__GetCalCancelSession *, const char*, const char*);
SOAP_FMAC3 struct ns__GetCalCancelSession * SOAP_FMAC4 soap_in_ns__GetCalCancelSession(struct soap*, const char*, struct ns__GetCalCancelSession *, const char*);
SOAP_FMAC5 struct ns__GetCalCancelSession * SOAP_FMAC6 soap_new_ns__GetCalCancelSession(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__GetCalCancelSession(struct soap*, struct ns__GetCalCancelSession*);
SOAP_FMAC3 struct ns__GetCalCancelSession * SOAP_FMAC4 soap_instantiate_ns__GetCalCancelSession(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__GetCalCancelSession(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__GetCalCancelSessionResponse
#define SOAP_TYPE_ns__GetCalCancelSessionResponse (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__GetCalCancelSessionResponse(struct soap*, struct ns__GetCalCancelSessionResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__GetCalCancelSessionResponse(struct soap*, const struct ns__GetCalCancelSessionResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__GetCalCancelSessionResponse(struct soap*, const struct ns__GetCalCancelSessionResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__GetCalCancelSessionResponse(struct soap*, const char*, int, const struct ns__GetCalCancelSessionResponse *, const char*);
SOAP_FMAC3 struct ns__GetCalCancelSessionResponse * SOAP_FMAC4 soap_get_ns__GetCalCancelSessionResponse(struct soap*, struct ns__GetCalCancelSessionResponse *, const char*, const char*);
SOAP_FMAC3 struct ns__GetCalCancelSessionResponse * SOAP_FMAC4 soap_in_ns__GetCalCancelSessionResponse(struct soap*, const char*, struct ns__GetCalCancelSessionResponse *, const char*);
SOAP_FMAC5 struct ns__GetCalCancelSessionResponse * SOAP_FMAC6 soap_new_ns__GetCalCancelSessionResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__GetCalCancelSessionResponse(struct soap*, struct ns__GetCalCancelSessionResponse*);
SOAP_FMAC3 struct ns__GetCalCancelSessionResponse * SOAP_FMAC4 soap_instantiate_ns__GetCalCancelSessionResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__GetCalCancelSessionResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__GetCalQueryStatus
#define SOAP_TYPE_ns__GetCalQueryStatus (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__GetCalQueryStatus(struct soap*, struct ns__GetCalQueryStatus *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__GetCalQueryStatus(struct soap*, const struct ns__GetCalQueryStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__GetCalQueryStatus(struct soap*, const struct ns__GetCalQueryStatus *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__GetCalQueryStatus(struct soap*, const char*, int, const struct ns__GetCalQueryStatus *, const char*);
SOAP_FMAC3 struct ns__GetCalQueryStatus * SOAP_FMAC4 soap_get_ns__GetCalQueryStatus(struct soap*, struct ns__GetCalQueryStatus *, const char*, const char*);
SOAP_FMAC3 struct ns__GetCalQueryStatus * SOAP_FMAC4 soap_in_ns__GetCalQueryStatus(struct soap*, const char*, struct ns__GetCalQueryStatus *, const char*);
SOAP_FMAC5 struct ns__GetCalQueryStatus * SOAP_FMAC6 soap_new_ns__GetCalQueryStatus(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__GetCalQueryStatus(struct soap*, struct ns__GetCalQueryStatus*);
SOAP_FMAC3 struct ns__GetCalQueryStatus * SOAP_FMAC4 soap_instantiate_ns__GetCalQueryStatus(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__GetCalQueryStatus(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__GetCalQueryStatusResponse
#define SOAP_TYPE_ns__GetCalQueryStatusResponse (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__GetCalQueryStatusResponse(struct soap*, struct ns__GetCalQueryStatusResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__GetCalQueryStatusResponse(struct soap*, const struct ns__GetCalQueryStatusResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__GetCalQueryStatusResponse(struct soap*, const struct ns__GetCalQueryStatusResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__GetCalQueryStatusResponse(struct soap*, const char*, int, const struct ns__GetCalQueryStatusResponse *, const char*);
SOAP_FMAC3 struct ns__GetCalQueryStatusResponse * SOAP_FMAC4 soap_get_ns__GetCalQueryStatusResponse(struct soap*, struct ns__GetCalQueryStatusResponse *, const char*, const char*);
SOAP_FMAC3 struct ns__GetCalQueryStatusResponse * SOAP_FMAC4 soap_in_ns__GetCalQueryStatusResponse(struct soap*, const char*, struct ns__GetCalQueryStatusResponse *, const char*);
SOAP_FMAC5 struct ns__GetCalQueryStatusResponse * SOAP_FMAC6 soap_new_ns__GetCalQueryStatusResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__GetCalQueryStatusResponse(struct soap*, struct ns__GetCalQueryStatusResponse*);
SOAP_FMAC3 struct ns__GetCalQueryStatusResponse * SOAP_FMAC4 soap_instantiate_ns__GetCalQueryStatusResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__GetCalQueryStatusResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__GetCalSearchCal
#define SOAP_TYPE_ns__GetCalSearchCal (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__GetCalSearchCal(struct soap*, struct ns__GetCalSearchCal *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__GetCalSearchCal(struct soap*, const struct ns__GetCalSearchCal *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__GetCalSearchCal(struct soap*, const struct ns__GetCalSearchCal *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__GetCalSearchCal(struct soap*, const char*, int, const struct ns__GetCalSearchCal *, const char*);
SOAP_FMAC3 struct ns__GetCalSearchCal * SOAP_FMAC4 soap_get_ns__GetCalSearchCal(struct soap*, struct ns__GetCalSearchCal *, const char*, const char*);
SOAP_FMAC3 struct ns__GetCalSearchCal * SOAP_FMAC4 soap_in_ns__GetCalSearchCal(struct soap*, const char*, struct ns__GetCalSearchCal *, const char*);
SOAP_FMAC5 struct ns__GetCalSearchCal * SOAP_FMAC6 soap_new_ns__GetCalSearchCal(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__GetCalSearchCal(struct soap*, struct ns__GetCalSearchCal*);
SOAP_FMAC3 struct ns__GetCalSearchCal * SOAP_FMAC4 soap_instantiate_ns__GetCalSearchCal(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__GetCalSearchCal(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__GetCalSearchCalResponse
#define SOAP_TYPE_ns__GetCalSearchCalResponse (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__GetCalSearchCalResponse(struct soap*, struct ns__GetCalSearchCalResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__GetCalSearchCalResponse(struct soap*, const struct ns__GetCalSearchCalResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__GetCalSearchCalResponse(struct soap*, const struct ns__GetCalSearchCalResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__GetCalSearchCalResponse(struct soap*, const char*, int, const struct ns__GetCalSearchCalResponse *, const char*);
SOAP_FMAC3 struct ns__GetCalSearchCalResponse * SOAP_FMAC4 soap_get_ns__GetCalSearchCalResponse(struct soap*, struct ns__GetCalSearchCalResponse *, const char*, const char*);
SOAP_FMAC3 struct ns__GetCalSearchCalResponse * SOAP_FMAC4 soap_in_ns__GetCalSearchCalResponse(struct soap*, const char*, struct ns__GetCalSearchCalResponse *, const char*);
SOAP_FMAC5 struct ns__GetCalSearchCalResponse * SOAP_FMAC6 soap_new_ns__GetCalSearchCalResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__GetCalSearchCalResponse(struct soap*, struct ns__GetCalSearchCalResponse*);
SOAP_FMAC3 struct ns__GetCalSearchCalResponse * SOAP_FMAC4 soap_instantiate_ns__GetCalSearchCalResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__GetCalSearchCalResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__GetCalOpenSession
#define SOAP_TYPE_ns__GetCalOpenSession (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__GetCalOpenSession(struct soap*, struct ns__GetCalOpenSession *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__GetCalOpenSession(struct soap*, const struct ns__GetCalOpenSession *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__GetCalOpenSession(struct soap*, const struct ns__GetCalOpenSession *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__GetCalOpenSession(struct soap*, const char*, int, const struct ns__GetCalOpenSession *, const char*);
SOAP_FMAC3 struct ns__GetCalOpenSession * SOAP_FMAC4 soap_get_ns__GetCalOpenSession(struct soap*, struct ns__GetCalOpenSession *, const char*, const char*);
SOAP_FMAC3 struct ns__GetCalOpenSession * SOAP_FMAC4 soap_in_ns__GetCalOpenSession(struct soap*, const char*, struct ns__GetCalOpenSession *, const char*);
SOAP_FMAC5 struct ns__GetCalOpenSession * SOAP_FMAC6 soap_new_ns__GetCalOpenSession(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__GetCalOpenSession(struct soap*, struct ns__GetCalOpenSession*);
SOAP_FMAC3 struct ns__GetCalOpenSession * SOAP_FMAC4 soap_instantiate_ns__GetCalOpenSession(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__GetCalOpenSession(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__GetCalOpenSessionResponse
#define SOAP_TYPE_ns__GetCalOpenSessionResponse (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__GetCalOpenSessionResponse(struct soap*, struct ns__GetCalOpenSessionResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__GetCalOpenSessionResponse(struct soap*, const struct ns__GetCalOpenSessionResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__GetCalOpenSessionResponse(struct soap*, const struct ns__GetCalOpenSessionResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__GetCalOpenSessionResponse(struct soap*, const char*, int, const struct ns__GetCalOpenSessionResponse *, const char*);
SOAP_FMAC3 struct ns__GetCalOpenSessionResponse * SOAP_FMAC4 soap_get_ns__GetCalOpenSessionResponse(struct soap*, struct ns__GetCalOpenSessionResponse *, const char*, const char*);
SOAP_FMAC3 struct ns__GetCalOpenSessionResponse * SOAP_FMAC4 soap_in_ns__GetCalOpenSessionResponse(struct soap*, const char*, struct ns__GetCalOpenSessionResponse *, const char*);
SOAP_FMAC5 struct ns__GetCalOpenSessionResponse * SOAP_FMAC6 soap_new_ns__GetCalOpenSessionResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__GetCalOpenSessionResponse(struct soap*, struct ns__GetCalOpenSessionResponse*);
SOAP_FMAC3 struct ns__GetCalOpenSessionResponse * SOAP_FMAC4 soap_instantiate_ns__GetCalOpenSessionResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__GetCalOpenSessionResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerTobool
#define SOAP_TYPE_PointerTobool (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTobool(struct soap*, bool *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTobool(struct soap*, bool *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTobool(struct soap*, const char *, int, bool *const*, const char *);
SOAP_FMAC3 bool ** SOAP_FMAC4 soap_get_PointerTobool(struct soap*, bool **, const char*, const char*);
SOAP_FMAC3 bool ** SOAP_FMAC4 soap_in_PointerTobool(struct soap*, const char*, bool **, const char*);

#ifndef SOAP_TYPE_PointerTostring
#define SOAP_TYPE_PointerTostring (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostring(struct soap*, char **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostring(struct soap*, char **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostring(struct soap*, const char *, int, char **const*, const char *);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_get_PointerTostring(struct soap*, char ***, const char*, const char*);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_in_PointerTostring(struct soap*, const char*, char ***, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#endif

/* End of soapH.h */
