/* soapsclwsObject.h
   Generated by gSOAP 2.7.11 from ../include/sclwsWS.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapsclwsObject_H
#define soapsclwsObject_H
#include "soapH.h"

/******************************************************************************\
 *                                                                            *
 * Service Object                                                             *
 *                                                                            *
\******************************************************************************/

extern SOAP_NMAC struct Namespace soap_namespaces[];
class sclwsService : public soap
{    public:
	sclwsService()
	{ this->namespaces = soap_namespaces; };
	virtual ~sclwsService() { };
	/// Bind service to port (returns master socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET bind(const char *host, int port, int backlog) { return soap_bind(this, host, port, backlog); };
	/// Accept next request (returns socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET accept() { return soap_accept(this); };
	/// Serve this request (returns error code or SOAP_OK)
	virtual	int serve() { return soap_serve(this); };
};

/******************************************************************************\
 *                                                                            *
 * Service Operations (you should define these globally)                      *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 ns__GetCalOpenSession(struct soap*, char **_param_1);

SOAP_FMAC5 int SOAP_FMAC6 ns__GetCalSearchCal(struct soap*, char *_param_2, char *_param_3, char **_param_4);

SOAP_FMAC5 int SOAP_FMAC6 ns__GetCalQueryStatus(struct soap*, char *_param_5, char **_param_6);

SOAP_FMAC5 int SOAP_FMAC6 ns__GetCalCancelSession(struct soap*, char *_param_7, bool *_param_8);

SOAP_FMAC5 int SOAP_FMAC6 ns__GetStar(struct soap*, char *query, char **output);

SOAP_FMAC5 int SOAP_FMAC6 ns__GetServerStatus(struct soap*, char **status);

#endif
